version: "3"

networks:
  backend:
  proxy-network:
    external: true

volumes:
  db:
  app:

secrets:
  postgres_db:
    file: "./secrets/postgres_db"
  postgres_user:
    file: "./secrets/postgres_user"
  postgres_password:
    file: "./secrets/postgres_password"

services:
  db:
    image: "postgres:15-alpine"
    restart: "unless-stopped"
    networks:
      - "backend"
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB_FILE=/run/secrets/postgres_db"
      - "POSTGRES_USER_FILE=/run/secrets/postgres_user"
      - "POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password"
    secrets:
      - "postgres_db"
      - "postgres_password"
      - "postgres_user"

  app:
    image: "nextcloud:25"
    restart: "unless-stopped"
    networks:
      - "backend"
      - "proxy-network"
    volumes:
      - "app:/var/www/html"
    environment:
      - "POSTGRES_HOST=db"
      - "POSTGRES_DB_FILE=/run/secrets/postgres_db"
      - "POSTGRES_USER_FILE=/run/secrets/postgres_user"
      - "POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password"
      - "TRUSTED_PROXIES=${TRUSTED_PROXIES}"
    secrets:
      - "postgres_db"
      - "postgres_password"
      - "postgres_user"
    depends_on:
      - "db"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_HOST}`)"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-redirectregex"
      - "traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.permanent=true"
      - "traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.replacement=https://$${1}/remote.php/dav/"
